plugin_names: 
    {
        SMART_Board_serial : hw_interface_plugin_SMART_Board,
    }
    
SMART_Board_serial:
    {
        SMART_Board : "SMART_Board",
    }
    
SMART_Board:
    {
        deviceName         : "/dev/ttyUSB1",
        baudrate           : 115200,
        subscribeToTopic   : "/example/subscribe",
        imuTopic           : "/smart2_01/imu/data",
        magTopic           : "/smart2_01/mag/data",
        tempTopic          : "/smart2_01/temp/data",
    }


